name: PR CI

on:
  pull_request:
    branches:
      - dev
      - main
      - 'feature/**'
      - 'hotfix/**'

jobs:
  django-tests:
    name: Django Backend Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run migrations check
        working-directory: backend
        run: python manage.py makemigrations --check --dry-run
