name: PR CI

on:
  pull_request:
    branches:
      - main
      - dev
      - 'feature/**'
      - 'hotfix/**'

jobs:
  django-tests:
    name: Django Backend Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r django/requirements.txt

      - name: Run migrations check
        working-directory: django
        run: python manage.py makemigrations --check --dry-run

      - name: Run Django tests
        working-directory: django
        run: pytest -q

  react-tests:
    name: React Frontend Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: web
        run: npm ci

      - name: Lint React code
        working-directory: web
        run: npm run lint --if-present

      - name: Run React tests
        working-directory: web
        run: npm test -- --watchAll=false

      - name: Build React app
        working-directory: web
        run: npm run build
